//client.houseinfo.action


// let ss = '[{"Id":0,"Name":"Vape","Icon":"inv-item-Vape","Price":"525$","ItemId":225},{"Id":1,"Name":"Ball","Icon":"inv-item-ball","Price":"800$","ItemId":263},{"Id":2,"Name":"Bong","Icon":"inv-item-bong","Price":"550$","ItemId":229},{"Id":3,"Name":"Hookah","Icon":"inv-item-hookah","Price":"2500$","ItemId":249},{"Id":4,"Name":"Bag","Icon":"inv-item-backpack","Price":"7500$","ItemId":-5},{"Id":5,"Name":"Beer","Icon":"inv-item-beer","Price":"80$","ItemId":4},{"Id":6,"Name":"Binoculars","Icon":"inv-item-binoculars","Price":"850$","ItemId":228},{"Id":7,"Name":"Camera","Icon":"inv-item-camera","Price":"750$","ItemId":231},{"Id":8,"Name":"Chips","Icon":"inv-item-Chips","Price":"30$","ItemId":3},{"Id":9,"Name":"Flashlight","Icon":"inv-item-Flashlight","Price":"170$","ItemId":191},{"Id":10,"Name":"Gas Can","Icon":"inv-item-gasoline","Price":"120$","ItemId":2},{"Id":11,"Name":"Guitar","Icon":"inv-item-guitar","Price":"1600$","ItemId":233},{"Id":12,"Name":"Hammer","Icon":"inv-item-Hammer","Price":"170$","ItemId":182},{"Id":13,"Name":"Key Ring","Icon":"inv-item-key-2","Price":"400$","ItemId":41},{"Id":15,"Name":"Love Note","Icon":"inv-item-LoveNote","Price":"600$","ItemId":224},{"Id":16,"Name":"Microphone","Icon":"inv-item-microphone","Price":"500$","ItemId":232},{"Id":17,"Name":"Crowbar","Icon":"inv-item-crowbar","Price":"170$","ItemId":184},{"Id":18,"Name":"Note","Icon":"inv-item-Note","Price":"400$","ItemId":223},{"Id":19,"Name":"Radio","Icon":"hud__icon-walkie-talkie","Price":"1300$","ItemId":243},{"Id":20,"Name":"Rose","Icon":"inv-item-rose","Price":"400$","ItemId":226},{"Id":21,"Name":"Umbrella","Icon":"inv-item-umbrella","Price":"700$","ItemId":230},{"Id":22,"Name":"Wrench","Icon":"inv-item-Pipe-Wrench","Price":"750$","ItemId":194},{"Id":23,"Name":"SIM Card","Icon":"inv-item-SimCard","Price":"170$","ItemId":271}]'
// store.smOpen("STORE", "_titleIcon", "_btn", ss)
// ng mat circle -1786.3385, 3089.6826, 32.805424

var store = new Vue({
    el: '.Main',

    data: {
        items: {
                "Debug": 0,
                "HealthKit": 1,
                "Gas Can": 2,
                "Crisps": 3,
                "Beer": 4,
                "Pizza": 5,
                "Burger": 6,
                "HotDog": 7,
                "Sandwich": 8,
                "eCola": 9,
                "Sprunk": 10,
                "Lockpick": 11,
                "BagWithMoney": 12,
                "Material": 13,
                "Drugs": 14,
                "BagWithDrill": 15,
                "ArmyLockpick": 16,
                "Pocket": 17,
                "Cuffs": 18,
                "CarKey": 19,
                "RusDrink1": 20,
                "RusDrink2": 21,
                "RusDrink3": 22,
                "YakDrink1": 23,
                "YakDrink2": 24,
                "YakDrink3": 25,
                "LcnDrink1": 26,
                "LcnDrink2": 27,
                "LcnDrink3": 28,
                "ArmDrink1": 29,
                "ArmDrink2": 30,
                "ArmDrink3": 31,
                "Present": 40,
                "Key Ring": 41,
                "Pistol": 100,
                "CombatPistol": 101,
                "Pistol50": 102,
                "SNSPistol": 103,
                "HeavyPistol": 104,
                "VintagePistol": 105,
                "MarksmanPistol": 106,
                "Revolver": 107,
                "APPistol": 108,
                "StunGun": 109,
                "FlareGun": 110,
                "DoubleAction": 111,
                "PistolMk2": 112,
                "SNSPistolMk2": 113,
                "RevolverMk2": 114,
                "MicroSMG": 115,
                "MachinePistol": 116,
                "SMG": 117,
                "AssaultSMG": 118,
                "CombatPDW": 119,
                "MG": 120,
                "CombatMG": 121,
                "Gusenberg": 122,
                "MiniSMG": 123,
                "SMGMk2": 124,
                "CombatMGMk2": 125,
                "AssaultRifle": 126,
                "CarbineRifle": 127,
                "AdvancedRifle": 128,
                "SpecialCarbine": 129,
                "BullpupRifle": 130,
                "CompactRifle": 131,
                "AssaultRifleMk2": 132,
                "CarbineRifleMk2": 133,
                "SpecialCarbineMk2": 134,
                "BullpupRifleMk2": 135,
                "SniperRifle": 136,
                "HeavySniper": 137,
                "MarksmanRifle": 138,
                "HeavySniperMk2": 139,
                "MarksmanRifleMk2": 140,
                "PumpShotgun": 141,
                "SawnOffShotgun": 142,
                "BullpupShotgun": 143,
                "AssaultShotgun": 144,
                "Musket": 145,
                "HeavyShotgun": 146,
                "DoubleBarrelShotgun": 147,
                "SweeperShotgun": 148,
                "PumpShotgunMk2": 149,
                "RayPistol": 150,
                "CeramicPistol": 151,
                "NavyRevolver": 152,
                "RayCarbine": 153,
                "GrenadeLauncher": 154,
                "RPG": 155,
                "Minigun": 156,
                "Firework": 157,
                "Railgun": 158,
                "HomingLauncher": 159,
                "GrenadeLauncherSmoke": 160,
                "CompactGrenadeLauncher": 161,
                "Widowmaker": 162,
                "Knife": 180,
                "Nightstick": 181,
                "Hammer": 182,
                "Bat": 183,
                "Crowbar": 184,
                "GolfClub": 185,
                "Bottle": 186,
                "Dagger": 187,
                "Hatchet": 188,
                "KnuckleDuster": 189,
                "Machete": 190,
                "Flashlight": 191,
                "SwitchBlade": 192,
                "PoolCue": 193,
                "Wrench": 194,
                "BattleAxe": 195,
                "PistolAmmo": 200,
                "SMGAmmo": 201,
                "RiflesAmmo": 202,
                "SniperAmmo": 203,
                "ShotgunsAmmo": 204,
                "Snowball": 205,
                "cVarmod": 206,
                "cClip": 207,
                "cSuppressor": 208,
                "cScope": 209,
                "cMuzzlebrake": 210,
                "cBarrel": 211,
                "cFlashlight": 212,
                "cGrip": 213,
                "cCamo": 214,
                "HalloweenCoin": 215,
                "Firework1": 216,
                "Firework2": 217,
                "Firework3": 218,
                "Firework4": 219,
                "CarCoupon": 220,
                "MerryChristmasCoin": 221,
                "Bear": 222,
                "Note": 223,
                "Love Note": 224,
                "Vape": 225,
                "Rose": 226,
                "Barbell": 227,
                "Binoculars": 228,
                "Bong": 229,
                "Umbrella": 230,
                "Camera": 231,
                "Microphone": 232,
                "Guitar": 233,
                "Pickaxe1": 234,
                "Pickaxe2": 235,
                "Pickaxe3": 236,
                "Coal": 237,
                "Iron": 238,
                "Gold": 239,
                "Sulfur": 240,
                "Emerald": 241,
                "Ruby": 242,
                "Radio": 243,
                "WorkAxe": 244,
                "WoodOak": 245,
                "WoodMaple": 246,
                "WoodPine": 247,
                "Boombox": 248,
                "Hookah": 249,
                "Case0": 250,
                "Case1": 251,
                "Case2": 252,
                "Case3": 253,
                "Case4": 254,
                "Case5": 255,
                "Case6": 256,
                "Case7": 257,
                "Case8": 258,
                "Case9": 259,
                "Case10": 260,
                "Case11": 261,
                "Case12": 262,
                "Ball": 263,
                "SummerCoin": 264,
                "Case13": 265,
                "MilitaryRifle": 266,
                "CandyCane": 267,
                "Case14": 268,
                "Qr": 269,
                "QrFake": 270,
                "Sim Card": 271,
                "VehicleNumber": 272,
                "Bint": 273,
                "Cocaine": 274,
                "Rub100": 275,
                "Rub200": 276,
                "Rub500": 277,
                "Rub1000": 278,
                "RadioInterceptor": 279,
                "Epinephrine": 280,
                "Case15": 281,
                "Case16": 282,
                "Case17": 283,
                "Case18": 284,
                "Case19": 285,
                "Case20": 286,
                "Case21": 287,
                "AppleCoin": 288,
                "Fire": 289,
                "Matras": 290,
                "Tent": 291,
                "Lezhak": 292,
                "Towel": 293,
                "Flag": 294,
                "Barrell": 295,
                "Surf": 296,
                "Vedro": 297,
                "Flagstok": 298,
                "Tenttwo": 299,
                "Polotence": 300,
                "Beachbag": 301,
                "Zontik": 302,
                "Zontiktwo": 303,
                "Zontikthree": 304,
                "Closedzontik": 305,
                "Vball": 306,
                "Bball": 307,
                "Boomboxxx": 308,
                "Table": 309,
                "Tabletwo": 310,
                "Tablethree": 311,
                "Tablefour": 312,
                "Chair": 313,
                "Chairtwo": 314,
                "Chaierthree": 315,
                "Chaierfour": 316,
                "Chairtable": 317,
                "Korzina": 318,
                "Light": 319,
                "Alco": 320,
                "Alcotwo": 321,
                "Alcothree": 322,
                "Alcofour": 323,
                "Cocktail": 324,
                "Cocktailtwo": 325,
                "Fruit": 326,
                "Fruittwo": 327,
                "Packet": 328,
                "Buter": 329,
                "Patatoes": 330,
                "Coffee": 331,
                "Podnosfood": 332,
                "Bbqtwo": 333,
                "Bbq": 334,
                "Vaza": 335,
                "Flagwtokk": 336,
                "Flagau": 337,
                "Flagbr": 338,
                "Flagch": 339,
                "Flagcz": 340,
                "Flageng": 341,
                "Flageu": 342,
                "Flagfr": 343,
                "Flagger": 344,
                "Flagire": 345,
                "Flagisr": 346,
                "Flagit": 347,
                "Flagjam": 348,
                "Flagjap": 349,
                "Flagmex": 350,
                "Flagnet": 351,
                "Flagnig": 352,
                "Flagnorw": 353,
                "Flagpol": 354,
                "Flagrus": 355,
                "Flagbel": 356,
                "Flagscot": 357,
                "Flagscr": 358,
                "Flagslovak": 359,
                "Flagslov": 360,
                "Flagsou": 361,
                "Flagspain": 362,
                "Flagswede": 363,
                "Flagswitz": 364,
                "Flagturk": 365,
                "Flaguk": 366,
                "Flagus": 367,
                "Flagwales": 368,
                "Flagfin": 369,
                "Flowerrr": 370,
                "Konus": 371,
                "Konuss": 372,
                "Otboynik1": 373,
                "Otboynik2": 374,
                "Dontcross": 375,
                "Stop": 376,
                "NetProezda": 377,
                "Kpp": 378,
                "Zabor1": 379,
                "Zabor2": 380,
                "Airlight": 381,
                "Camera1": 382,
                "Camera2": 383,
                "TacticalRifle": 384,
                "PrecisionRifle": 385,
                "CombatShotgun": 386,
                "HeavyRifle": 387,
                "NeonStick": 388,
                "Glowstick": 389,
                "Giftcoin": 390,
                "CombatRifle": 391,
                "Glock": 392,
                "WheatPlant": 393,
                "WheatSeed": 394,
                "PumkinPlant": 395,
                "PumkinSeed": 396,
                "FlaxSeed": 397,
                "Cumin": 398,
                "CoffeeBeen": 399,
                "CabbagePlant": 400,
                "Bracelets": -15,
                "Watches": -14,
                "Glasses": -13,
                "Hat": -12,
                "Top": -11,
                "Decals": -10,
                "BodyArmor": -9,
                "Undershit": -8,
                "Jewelry": -7,
                "Feet": -6,
                "Bag": -5,
                "Leg": -4,
                "Gloves": -3,
                "Ears": -2,
                "Mask": -1
        },
        title: '',
        searchQuery: '',
        titleIcon: '',
        elements: [],
        type: 0,
        alerttimer: undefined,
        alerts: "",
        activeCategory: 'საჭმელი',
        categories:{
            "საჭმელი": [
            { "Id": 5, "Name": "Pizza", "Icon": "inv-item-pizza", "Price": "150$" },
            { "Id": 6, "Name": "Burger", "Icon": "inv-item-burger", "Price": "120$" },
            { "Id": 7, "Name": "HotDog", "Icon": "inv-item-hotdog", "Price": "90$" },
            { "Id": 8, "Name": "Sandwich", "Icon": "inv-item-sandwich", "Price": "80$" },
            { "Id": 3, "Name": "Crisps", "Icon": "inv-item-crisps", "Price": "40$" },
            { "Id": 329, "Name": "Buter", "Icon": "inv-item-buter", "Price": "50$" },
            { "Id": 330, "Name": "Patatoes", "Icon": "inv-item-patatoes", "Price": "60$" },
            { "Id": 332, "Name": "Podnosfood", "Icon": "inv-item-podnosfood", "Price": "200$" },
            ],
            "სასმელი": [
            { "Id": 4, "Name": "Beer", "Icon": "inv-item-beer", "Price": "80$" },
            { "Id": 9, "Name": "eCola", "Icon": "inv-item-eCola", "Price": "50$" },
            { "Id": 10, "Name": "Sprunk", "Icon": "inv-item-sprunk", "Price": "50$" },
            { "Id": 331, "Name": "Coffee", "Icon": "inv-item-coffee", "Price": "60$" }
            ],
            "ელექტრონიკა": [
                { "Id": 7, "Name": "Camera", "Icon": "inv-item-camera", "Price": "750$", "ItemId": 231 },
                { "Id": 19, "Name": "Radio", "Icon": "hud__icon-walkie-talkie", "Price": "1300$", "ItemId": 243 },
                { "Id": 16, "Name": "Microphone", "Icon": "inv-item-microphone", "Price": "500$", "ItemId": 232 },
                { "Id": 23, "Name": "SIM Card", "Icon": "inv-item-SimCard", "Price": "170$", "ItemId": 271 }
            ],
            "ინვენტარი": [
                { "Id": 4, "Name": "Bag", "Icon": "inv-item-backpack", "Price": "7500$", "ItemId": -5 },
                { "Id": 21, "Name": "Umbrella", "Icon": "inv-item-umbrella", "Price": "700$", "ItemId": 230 },
                { "Id": 6, "Name": "Binoculars", "Icon": "inv-item-binoculars", "Price": "850$", "ItemId": 228 },
                { "Id": 11, "Name": "Guitar", "Icon": "inv-item-guitar", "Price": "1600$", "ItemId": 233 },
                { "Id": 13, "Name": "Key Ring", "Icon": "inv-item-key-2", "Price": "400$", "ItemId": 41 },
            ],

            "ხელსაწყოები": [
                { "Id": 9, "Name": "Flashlight", "Icon": "inv-item-Flashlight", "Price": "170$", "ItemId": 191 },
                { "Id": 12, "Name": "Hammer", "Icon": "inv-item-Hammer", "Price": "170$", "ItemId": 182 },
                { "Id": 17, "Name": "Crowbar", "Icon": "inv-item-crowbar", "Price": "170$", "ItemId": 184 },
                { "Id": 22, "Name": "Wrench", "Icon": "inv-item-Pipe-Wrench", "Price": "750$", "ItemId": 194 },
                { "Id": 10, "Name": "Gas Can", "Icon": "inv-item-gasoline", "Price": "120$", "ItemId": 2 }
            ]
        },
        cloud: "https://franko.rostevan.space/test/cloud/inventoryItems/items/",
    },

    computed: {
        filteredProducts() {
            let products = this.categories[this.activeCategory] || [];
            if (this.searchQuery) {
                return products.filter(p => p.Name.toLowerCase().includes(this.searchQuery.toLowerCase()));
            }
            return products;
        }
    },

    methods: {
        smOpen(_title, _titleIcon, _btn, _json, _type = 0) {
            this.title = _title;
            this.titleIcon = _titleIcon;
            this.btn = _btn;
            try {
                this.elements = JSON.parse(_json);
            } catch(e) {
                this.elements = [];
                console.error('JSON parse error:', e);
            }
            this.type = _type;

            let cats = {};
            this.elements.forEach(item => {
                let category = item.Category || 'სხვა';
                if (!cats[category]) cats[category] = [];
                cats[category].push(item);
            });
            this.categories = cats;
            this.activeCategory = Object.keys(cats)[0] || 'სხვა';
        },
        formatMoney(amount) {
            return amount.toLocaleString('en-US');
        },
        alart(msg) {
            this.alerts = msg;
            clearTimeout(this.alerttimer);
            this.alerttimer = setTimeout(() => {
                this.alerts = "";
            }, 5000);
        },
        errorImage(name) {
            let find = this.items[name];
            if(find === undefined) find = 0;
            return `${this.cloud}${find}.png`;
        },
        ItemSelect(id) {
            mp.trigger('client.sm.click', id);
        },
        Closemenu() {
            mp.trigger('client.sm.exit');
        },
        selectCategory(key) {
            this.activeCategory = key;
        }
    }
});